### ISSUE TITLE
Adding throttle to INSTALLED APPS in settings.py

### ISSUE THREAD

**Issue by mhb11** [sobotklp/django-throttle-requests#11]
Instead of adding throttle to my python path, would adding throttle to INSTALLED APPS work too?

**Comment by sobotklp** [comment]
As long as you can import throttle from your view code, it should work just fine. Adding it to PYTHONPATH just makes importing more convenient, but it is optional.

Django-throttle-requests doesn't need to be added to INSTALLED_APPS because it contains no views, models or checks for your application.

**Comment by sobotklp** [comment]
Closing this. Feel free to reopen if you have further questions.
